/*
 * Secalot firmware.
 * Copyright (c) 2017 Matvey Mukha <matvey.mukha@gmail.com>
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef __MK82_USB_DEVICE_DESCRIPTOR_H__
#define __MK82_USB_DEVICE_DESCRIPTOR_H__

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/* Device */
#define MK82_USB_DEVICE_CLASS (0x00)
#define MK82_USB_DEVICE_SUBCLASS (0x00)
#define MK82_USB_DEVICE_PROTOCOL (0x00)

#define MK82_USB_DEVICE_CONFIGURATION_COUNT (1)
#define MK82_USB_DEVICE_STRING_COUNT (3)
#define MK82_USB_DEVICE_LANGUAGE_COUNT (1)

#define MK82_USB_DEVICE_SPECIFICATION_VERSION (0x0200)
#define MK82_USB_DEVICE_VERSION (0x0100U)
#define MK82_USB_DEVICE_MAX_POWER (0x32)

#define MK82_USB_DESCRIPTOR_LENGTH_STRING0 (4)
#define MK82_USB_DESCRIPTOR_LENGTH_STRING1 (16)

#ifdef FIRMWARE
#define MK82_USB_DESCRIPTOR_LENGTH_STRING2 (30)
#else /* FIRMWARE */
#define MK82_USB_DESCRIPTOR_LENGTH_STRING2 (38)
#endif /* FIRMWARE */

#ifdef FIRMWARE
#define MK82_USB_INTERFACE_COUNT (0x04)
#else /* FIRMWARE */
#define MK82_USB_INTERFACE_COUNT (0x01)
#endif /* FIRMWARE */

#define MK82_USB_DEFAULT_CONFIGURATION_VALUE (0x01)

#ifdef FIRMWARE
#define MK82_USB_TOTAL_CONFIGURATION_DESCRIPTOR_LENGTH                                  \
    ((1 * USB_DESCRIPTOR_LENGTH_CONFIGURE) + (1 * USB_DESCRIPTOR_LENGTH_INTERFACE) +    \
     (1 * CCID_DEVICE_CLASS_DESCRIPTOR_LENGTH) + (2 * USB_DESCRIPTOR_LENGTH_ENDPOINT) + \
     (1 * USB_DESCRIPTOR_LENGTH_INTERFACE) + (1 * MK82_USB_U2F_HID_DECRIPTOR_LENGTH) +  \
     (2 * USB_DESCRIPTOR_LENGTH_ENDPOINT) + (1 * USB_DESCRIPTOR_LENGTH_INTERFACE) +     \
     (1 * MK82_USB_KBD_HID_DECRIPTOR_LENGTH) + (1 * USB_DESCRIPTOR_LENGTH_ENDPOINT) +   \
     (1 * USB_DESCRIPTOR_LENGTH_INTERFACE) + (1 * MK82_USB_BTC_HID_DECRIPTOR_LENGTH) +  \
     (2 * USB_DESCRIPTOR_LENGTH_ENDPOINT))
#else /* FIRMWARE */
#define MK82_USB_TOTAL_CONFIGURATION_DESCRIPTOR_LENGTH                               \
    ((1 * USB_DESCRIPTOR_LENGTH_CONFIGURE) + (1 * USB_DESCRIPTOR_LENGTH_INTERFACE) + \
     (1 * CCID_DEVICE_CLASS_DESCRIPTOR_LENGTH) + (2 * USB_DESCRIPTOR_LENGTH_ENDPOINT))
#endif /* FIRMWARE */

/* CCID */
#define MK82_USB_CCID_INTERFACE_NUMBER (0x00)
#define MK82_USB_CCID_NUMBER_OF_ENDPOINTS (0x02)
#define MK82_USB_CCID_BULK_ENDPOINTS_PACKET_SIZE (0x40)
#define MK82_USB_CCID_BULK_IN_ENDPOINT (1)
#define MK82_USB_CCID_BULK_OUT_ENDPOINT (1)

#define MK82_USB_CCID_CLASS (0x0B)
#define MK82_USB_CCID_SUBCLASS (0x00)
#define MK82_USB_CCID_PROTOCOL (0x00)

#ifdef FIRMWARE

/* U2F */
#define MK82_USB_U2F_INTERFACE_NUMBER (0x01)
#define MK82_USB_U2F_NUMBER_OF_ENDPOINTS (0x02)

#define MK82_USB_U2F_CLASS (0x03)
#define MK82_USB_U2F_SUBCLASS (0x00)
#define MK82_USB_U2F_PROTOCOL (0x00)

#define MK82_USB_U2F_HID_DECRIPTOR_LENGTH (0x09)
#define MK82_USB_U2F_HID_DECRIPTOR_SPEC_RELEASE (0x100)
#define MK82_USB_U2F_HID_DECRIPTOR_COUNTRY_CODE (0x00)
#define MK82_USB_U2F_HID_DECRIPTOR_NUMBER_OF_DESCRIPTORS (0x01)

#define MK82_USB_U2F_INTERRUPT_IN_ENDPOINT (2)
#define MK82_USB_U2F_INTERRUPT_OUT_ENDPOINT (2)
#define MK82_USB_U2F_INTERRUPT_ENDPOINTS_PACKET_SIZE (0x40)
#define MK82_USB_U2F_INTERRUPT_ENDPOINTS_POLLING_INTERVAL (0x02)

/* Keyboard */
#define MK82_USB_KBD_INTERFACE_NUMBER (0x02)
#define MK82_USB_KBD_NUMBER_OF_ENDPOINTS (0x01)

#define MK82_USB_KBD_CLASS (0x03)
#define MK82_USB_KBD_SUBCLASS (0x00)
#define MK82_USB_KBD_PROTOCOL (0x00)

#define MK82_USB_KBD_HID_DECRIPTOR_LENGTH (0x09)
#define MK82_USB_KBD_HID_DECRIPTOR_SPEC_RELEASE (0x100)
#define MK82_USB_KBD_HID_DECRIPTOR_COUNTRY_CODE (0x00)
#define MK82_USB_KBD_HID_DECRIPTOR_NUMBER_OF_DESCRIPTORS (0x01)

#define MK82_USB_KBD_INTERRUPT_IN_ENDPOINT (3)
#define MK82_USB_KBD_INTERRUPT_ENDPOINT_PACKET_SIZE (0x08)
#define MK82_USB_KBD_INTERRUPT_ENDPOINT_POLLING_INTERVAL (0x0A)

/* BTC */

#define MK82_USB_BTC_INTERFACE_NUMBER (0x03)
#define MK82_USB_BTC_NUMBER_OF_ENDPOINTS (0x02)

#define MK82_USB_BTC_CLASS (0x03)
#define MK82_USB_BTC_SUBCLASS (0x00)
#define MK82_USB_BTC_PROTOCOL (0x00)

#define MK82_USB_BTC_HID_DECRIPTOR_LENGTH (0x09)
#define MK82_USB_BTC_HID_DECRIPTOR_SPEC_RELEASE (0x100)
#define MK82_USB_BTC_HID_DECRIPTOR_COUNTRY_CODE (0x00)
#define MK82_USB_BTC_HID_DECRIPTOR_NUMBER_OF_DESCRIPTORS (0x01)

#define MK82_USB_BTC_INTERRUPT_IN_ENDPOINT (4)
#define MK82_USB_BTC_INTERRUPT_OUT_ENDPOINT (4)
#define MK82_USB_BTC_INTERRUPT_ENDPOINTS_PACKET_SIZE (0x40)
#define MK82_USB_BTC_INTERRUPT_ENDPOINTS_POLLING_INTERVAL (0x05)

#endif /* FIRMWARE */

#endif /* __MK82_USB_DEVICE_DESCRIPTOR_H__ */
